const seasons = [
  "Survivor: Borneo",
  "Survivor: The Australian Outback",
  "Survivor: Africa",
  "Survivor: Marquesas",
  "Survivor: Thailand",
  "Survivor: The Amazon",
  "Survivor: Pearl Islands",
  "Survivor: All-Stars",
  "Survivor: Vanuatu",
  "Survivor: Palau",
  "Survivor: Guatemala",
  "Survivor: Panama",
  "Survivor: Cook Islands",
  "Survivor: Fiji",
  "Survivor: China",
  "Survivor: Micronesia",
  "Survivor: Gabon",
  "Survivor: Tocantins",
  "Survivor: Samoa",
  "Survivor: Heroes vs. Villains",
  "Survivor: Nicaragua",
  "Survivor: Redemption Island",
  "Survivor: South Pacific",
  "Survivor: One World",
  "Survivor: Philippines",
  "Survivor: Caramoan",
  "Survivor: Blood vs. Water",
  "Survivor: Cagayan",
  "Survivor: San Juan del Sur",
  "Survivor: Worlds Apart",
  "Survivor: Cambodia",
  "Survivor: Kaôh Rōng",
  "Survivor: Millennials vs. Gen X",
  "Survivor: Game Changers",
  "Survivor: Heroes vs. Healers vs. Hustlers",
  "Survivor: Ghost Island",
  "Survivor: David vs. Goliath",
  "Survivor: Edge of Extinction",
  "Survivor: Island of the Idols",
  "Survivor: Winners at War",
  "Survivor 41",
  "Survivor 42",
  "Survivor 43",
  "Survivor 44",
  "Survivor 45",
  "Survivor 46",
];
